### ISSUE TITLE
Polluted namespaces

### ISSUE THREAD

**Issue by ghost** [Adivius/Graphite#1]
https://github.com/Adivius/Graphite/blob/a7cadffdfb35faf635afbeab56db2b92f60b12f2/Core/EventScreen.java#L1
https://github.com/Adivius/Graphite/blob/a7cadffdfb35faf635afbeab56db2b92f60b12f2/Core/BufferedScreen.java#L1
https://github.com/Adivius/Graphite/blob/a7cadffdfb35faf635afbeab56db2b92f60b12f2/Core/Pen.java#L1
https://github.com/Adivius/Graphite/blob/a7cadffdfb35faf635afbeab56db2b92f60b12f2/Core/Screen.java#L1

All files' namespaces are heavily polluted

**Comment by Adivius** [comment]
Many aspects of these namespaces are used
