### ISSUE TITLE
Magic constants

### ISSUE THREAD

**Issue by ghost** [Adivius/Graphite#3]
https://github.com/Adivius/Graphite/blob/a7cadffdfb35faf635afbeab56db2b92f60b12f2/Core/Screen.java#L36
https://github.com/Adivius/Graphite/blob/a7cadffdfb35faf635afbeab56db2b92f60b12f2/Core/Screen.java#L70

**Comment by Adivius** [comment]
Closed in 9f1ffd13824d0b9b7babf26fd2f9d2723257f202
