### ISSUE TITLE
Window resizing shenanigans

### ISSUE THREAD

**Issue by ghost** [Adivius/Graphite#5]
https://github.com/Adivius/Graphite/blob/a7cadffdfb35faf635afbeab56db2b92f60b12f2/Core/Screen.java#L46

Weird calculations

https://github.com/Adivius/Graphite/blob/a7cadffdfb35faf635afbeab56db2b92f60b12f2/Core/Screen.java#L106
https://github.com/Adivius/Graphite/blob/a7cadffdfb35faf635afbeab56db2b92f60b12f2/Core/Screen.java#L111

Unintuitive function names

**Comment by Adivius** [comment]
Closed in 9f1ffd13824d0b9b7babf26fd2f9d2723257f202

**Comment by Adivius** [comment]
Closed in 9f1ffd13824d0b9b7babf26fd2f9d2723257f202
